//! GBNF grammar compiled from the *active* tool set each turn — never from the
//! full registry.
//!
//! The compiled grammar is cached by the hash of the active set. The set changes
//! rarely (focus switches, a pin), so this is nearly free.

use localspace_proto as proto;
use serde_json::Value as J;
use std::collections::HashMap;
use std::sync::Mutex;

/// Compiled grammar plus the key it was compiled under.
#[derive(Debug, Clone)]
pub struct Grammar {
    pub hash: String,
    pub gbnf: String,
}

#[derive(Default)]
pub struct GrammarCache {
    entries: Mutex<HashMap<String, Grammar>>,
}

impl GrammarCache {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn compile(&self, tools: &[proto::ExposedTool]) -> Grammar {
        let hash = active_set_hash(tools);
        if let Some(hit) = self.entries.lock().unwrap().get(&hash) {
            return hit.clone();
        }
        let grammar = Grammar {
            hash: hash.clone(),
            gbnf: to_gbnf(tools),
        };
        self.entries
            .lock()
            .unwrap()
            .insert(hash, grammar.clone());
        grammar
    }

    pub fn len(&self) -> usize {
        self.entries.lock().unwrap().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// Stable identity of an active set: the tool names and their schemas.
pub fn active_set_hash(tools: &[proto::ExposedTool]) -> String {
    let mut names: Vec<String> = tools
        .iter()
        .map(|t| format!("{}:{}", t.name, t.params))
        .collect();
    names.sort();
    blake3::hash(names.join("\n").as_bytes()).to_hex()[..16].to_string()
}

/// Compile the active set into a GBNF grammar that admits exactly one tool call.
pub fn to_gbnf(tools: &[proto::ExposedTool]) -> String {
    let mut out = String::new();
    out.push_str("# generated by localSpace Core from the active tool set\n");

    if tools.is_empty() {
        out.push_str("root ::= \"{}\"\n");
        return out;
    }

    let alts: Vec<String> = (0..tools.len()).map(|i| format!("call{i}")).collect();
    out.push_str(&format!("root ::= {}\n", alts.join(" | ")));

    for (i, tool) in tools.iter().enumerate() {
        out.push_str(&format!(
            "call{i} ::= \"{{\" ws \"\\\"tool\\\"\" ws \":\" ws \"\\\"{}\\\"\" ws \",\" ws \"\\\"params\\\"\" ws \":\" ws params{i} ws \"}}\"\n",
            tool.name
        ));
        out.push_str(&object_rule(&format!("params{i}"), &tool.params));
    }

    out.push_str(
        r#"string ::= "\"" char* "\""
char ::= [^"\\] | "\\" ["\\/bfnrt]
number ::= "-"? int frac? exp?
int ::= "0" | [1-9] [0-9]*
frac ::= "." [0-9]+
exp ::= [eE] [-+]? [0-9]+
boolean ::= "true" | "false"
null ::= "null"
value ::= string | number | boolean | null
ws ::= [ \t\n]*
"#,
    );
    out
}

/// One `{...}` rule for a tool's parameter schema.
///
/// Required properties are emitted in schema order and are mandatory; optional
/// ones follow and may be omitted. This is the subset the installer lint already
/// constrains schemas to (object roots, <= 8 properties, primitive leaves).
fn object_rule(name: &str, schema: &J) -> String {
    let props = schema.get("properties").and_then(|p| p.as_object());
    let Some(props) = props else {
        return format!("{name} ::= \"{{\" ws \"}}\"\n");
    };
    if props.is_empty() {
        return format!("{name} ::= \"{{\" ws \"}}\"\n");
    }

    let required: Vec<String> = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect()
        })
        .unwrap_or_default();

    let mut rules = String::new();
    let mut parts: Vec<String> = Vec::new();
    let mut first = true;

    // Required first, in schema order, then optional ones as `( "," pair )?`.
    let ordered: Vec<(&String, &J)> = props
        .iter()
        .filter(|(k, _)| required.contains(k))
        .chain(props.iter().filter(|(k, _)| !required.contains(k)))
        .collect();

    for (key, spec) in ordered {
        let sub = format!("{name}_{}", sanitize(key));
        rules.push_str(&leaf_rule(&sub, spec));
        let pair = format!("\"\\\"{key}\\\"\" ws \":\" ws {sub}");
        if required.contains(key) {
            if first {
                parts.push(format!("ws {pair}"));
                first = false;
            } else {
                parts.push(format!("ws \",\" ws {pair}"));
            }
        } else if first {
            // Everything is optional: allow the empty object too.
            parts.push(format!("( ws {pair} )?"));
        } else {
            parts.push(format!("( ws \",\" ws {pair} )?"));
        }
    }

    format!("{name} ::= \"{{\" {} ws \"}}\"\n{rules}", parts.join(" "))
}

fn leaf_rule(name: &str, spec: &J) -> String {
    if let Some(values) = spec.get("enum").and_then(|e| e.as_array()) {
        let alts: Vec<String> = values
            .iter()
            .map(|v| match v {
                J::String(s) => format!("\"\\\"{s}\\\"\""),
                other => format!("\"{other}\""),
            })
            .collect();
        if !alts.is_empty() {
            return format!("{name} ::= {}\n", alts.join(" | "));
        }
    }
    let ty = spec.get("type").and_then(|t| t.as_str()).unwrap_or("string");
    let body = match ty {
        "string" => "string".to_string(),
        "number" | "integer" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "null" => "null".to_string(),
        "array" => {
            let item_ty = spec
                .get("items")
                .and_then(|i| i.get("type"))
                .and_then(|t| t.as_str())
                .unwrap_or("string");
            let item = match item_ty {
                "number" | "integer" => "number",
                "boolean" => "boolean",
                "object" => "value",
                _ => "string",
            };
            format!("\"[\" ws ( {item} ( ws \",\" ws {item} )* )? ws \"]\"")
        }
        // Nested objects are not constrained beyond being JSON values: the lint
        // keeps schemas shallow, and over-constraining here would reject valid calls.
        _ => "value".to_string(),
    };
    format!("{name} ::= {body}\n")
}

fn sanitize(key: &str) -> String {
    key.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use localspace_proto::{Confirm, CostHint, ExposureReason, Json, ToolKind};

    fn tool(name: &str, params: J) -> proto::ExposedTool {
        proto::ExposedTool {
            harness: "io.localspace.whiteboard".into(),
            name: name.into(),
            summary: "does a thing".into(),
            params: Json(params),
            kind: ToolKind::Write,
            confirm: Confirm::Never,
            cost_hint: CostHint::Instant,
            undoable: true,
            reason: ExposureReason::Focused,
        }
    }

    #[test]
    fn the_grammar_lists_exactly_the_active_tools() {
        let tools = vec![
            tool("canvas.add_shape", serde_json::json!({
                "type": "object",
                "properties": {"kind": {"type": "string", "enum": ["rect", "ellipse"]}},
                "required": ["kind"]
            })),
            tool("canvas.clear", serde_json::json!({"type": "object", "properties": {}})),
        ];
        let g = to_gbnf(&tools);
        assert!(g.contains("root ::= call0 | call1"));
        assert!(g.contains("canvas.add_shape"));
        assert!(g.contains("canvas.clear"));
        // A tool that is not in the active set cannot appear.
        assert!(!g.contains("canvas.delete"));
        // The enum became a literal alternation, so the model cannot invent a value.
        assert!(g.contains(r#""\"rect\"" | "\"ellipse\"""#), "{g}");
    }

    #[test]
    fn an_empty_active_set_still_produces_a_valid_grammar() {
        let g = to_gbnf(&[]);
        assert!(g.contains("root ::="));
    }

    #[test]
    fn optional_params_stay_optional() {
        let tools = vec![tool(
            "canvas.move",
            serde_json::json!({
                "type": "object",
                "properties": {"id": {"type": "string"}, "dx": {"type": "number"}},
                "required": ["id"]
            }),
        )];
        let g = to_gbnf(&tools);
        assert!(g.contains(r#"( ws "," ws "\"dx\"" ws ":" ws params0_dx )?"#), "{g}");
    }

    #[test]
    fn the_cache_is_keyed_by_the_active_set_not_the_registry() {
        let cache = GrammarCache::new();
        let a = vec![tool("a.one", serde_json::json!({"type": "object", "properties": {}}))];
        let b = vec![tool("b.two", serde_json::json!({"type": "object", "properties": {}}))];

        let g1 = cache.compile(&a);
        let g2 = cache.compile(&a);
        assert_eq!(g1.hash, g2.hash);
        assert_eq!(cache.len(), 1, "the same active set must not recompile");

        let g3 = cache.compile(&b);
        assert_ne!(g1.hash, g3.hash);
        assert_eq!(cache.len(), 2);
    }

    #[test]
    fn the_hash_ignores_tool_ordering() {
        let a = tool("a.one", serde_json::json!({"type": "object", "properties": {}}));
        let b = tool("b.two", serde_json::json!({"type": "object", "properties": {}}));
        assert_eq!(
            active_set_hash(&[a.clone(), b.clone()]),
            active_set_hash(&[b, a])
        );
    }
}
