// The libraries the shell provides to harness frames through the import map
// (architecture v2.1 §6.3): one ES module each under `dist/_localspace/`,
// served on every harness origin beside the SDK. React, its JSX runtime and
// its DOM client are bundled together once, so every frame shares one React;
// `react/jsx-runtime` and `react-dom/client` are thin modules over that
// bundle. Run after the shell's own build.

import { build } from "vite";
import { resolve } from "node:path";
import { createRequire } from "node:module";
import { copyFileSync, existsSync, readdirSync, renameSync, writeFileSync } from "node:fs";

const root = process.cwd();
const outDir = resolve(root, "dist/_localspace");
const require = createRequire(import.meta.url);

const named = (specifier) =>
  Object.keys(require(specifier)).filter((k) => /^[A-Za-z_$][\w$]*$/.test(k) && k !== "default");

// React and its companions are CommonJS: `export * from` them carries no
// named exports through the bundler, and a companion that `require`s
// `react` cannot have it external in a browser module. So one generated
// entry bundles all three and names every export the modules have.
const reactEntry = resolve(root, "packages/libs/react.generated.ts");
writeFileSync(
  reactEntry,
  [
    "// Generated by scripts/build-libs.mjs: React, its JSX runtime and its DOM client,",
    "// bundled together so harness frames share one React. Not committed.",
    'import * as react from "react";',
    'import * as jsxRuntime from "react/jsx-runtime";',
    'import * as domClient from "react-dom/client";',
    "export default react;",
    `export const { ${named("react").join(", ")} } = react;`,
    "export const __jsxRuntime = jsxRuntime;",
    "export const __domClient = domClient;",
    "",
  ].join("\n"),
);

/** name → { entry, external } */
const libs = [
  { name: "react", entry: reactEntry, external: [] },
  { name: "canvas", entry: resolve(root, "packages/canvas/src/index.ts"), external: [] },
  { name: "ui", entry: resolve(root, "packages/ui/src/index.ts"), external: ["react", "react/jsx-runtime", "react-dom/client"] },
  { name: "automerge", entry: resolve(root, "packages/libs/automerge.ts"), external: [] },
];

let first = true;
for (const lib of libs) {
  if (!existsSync(lib.entry)) {
    console.log(`skip ${lib.name}: no ${lib.entry} yet`);
    continue;
  }
  await build({
    configFile: false,
    root,
    logLevel: "warn",
    define: { "process.env.NODE_ENV": JSON.stringify("production") },
    build: {
      outDir,
      emptyOutDir: first,
      target: "es2022",
      sourcemap: false,
      minify: true,
      lib: { entry: lib.entry, formats: ["es"], fileName: () => `${lib.name}.js`, cssFileName: lib.name },
      rollupOptions: {
        external: lib.external,
        output: { chunkFileNames: `${lib.name}-[hash].js`, assetFileNames: `${lib.name}-[hash][extname]` },
      },
    },
  });
  first = false;
  console.log(`built ${lib.name}.js`);
}

// The two companions, as modules over the React bundle.
const shim = (file, field, specifier) => {
  const keys = named(specifier);
  writeFileSync(
    resolve(outDir, file),
    [
      `// ${specifier}, over the shell's one React bundle.`,
      `import { ${field} as m } from "./react.js";`,
      "export default m;",
      `export const { ${keys.join(", ")} } = m;`,
      "",
    ].join("\n"),
  );
  console.log(`wrote ${file}`);
};
shim("react-jsx-runtime.js", "__jsxRuntime", "react/jsx-runtime");
shim("react-dom-client.js", "__domClient", "react-dom/client");

// The library's stylesheet keeps the library's name, whatever the bundler
// called it, because the harness page links it by that name.
for (const file of readdirSync(outDir)) {
  const m = /^(ui)-[A-Za-z0-9_-]+\.css$/.exec(file);
  if (m) renameSync(resolve(outDir, file), resolve(outDir, `${m[1]}.css`));
}

// Automerge loads its WebAssembly from beside its module, by this name.
const wasm = resolve(root, "node_modules/@automerge/automerge/dist/automerge.wasm");
if (existsSync(wasm)) copyFileSync(wasm, resolve(outDir, "automerge_wasm_bg.wasm"));
