//! The TypeScript client's types are generated from `proto`, never written by
//! hand (architecture v2 §5). Running this test writes them into the web
//! client's source tree; CI runs it and fails if the result differs from what
//! is committed.

use localspace_proto as proto;
use std::path::{Path, PathBuf};
use ts_rs::{Config, TS};

fn out_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/api/generated")
}

#[test]
fn typescript_bindings_are_generated_from_proto() {
    let dir = out_dir();
    std::fs::create_dir_all(&dir).expect("creating the generated directory");
    // Ids and counts are `u64` in Rust and plain numbers in JSON: `bigint`
    // would be wrong on the receiving side of `JSON.parse`.
    let cfg = Config::new().with_out_dir(&dir).with_large_int("number");

    // The envelope reaches everything: Body → Request, Response, Event → the
    // rest of the contract, dependency by dependency.
    proto::Envelope::export_all(&cfg).expect("exporting the contract");
    // `GET /api/v1/me` answers outside the envelope; its type is generated too.
    proto::Me::export_all(&cfg).expect("exporting Me");

    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .expect("reading the generated directory")
        .filter_map(|entry| {
            let name = entry.ok()?.file_name().into_string().ok()?;
            let stem = name.strip_suffix(".ts")?;
            (stem != "index").then(|| stem.to_string())
        })
        .collect();
    names.sort();
    let mut index = String::from(
        "// Generated by `cargo test -p localspace-proto` from crates/localspace-proto. Do not edit.\n",
    );
    for name in &names {
        index.push_str(&format!("export type {{ {name} }} from \"./{name}\";\n"));
    }
    std::fs::write(dir.join("index.ts"), index).expect("writing index.ts");

    let request = std::fs::read_to_string(dir.join("Request.ts")).expect("Request.ts");
    assert!(
        request.contains("get_environment"),
        "Request.ts must carry serde's names, not Rust's: {request}"
    );
    assert!(
        names.len() >= 40,
        "expected the whole contract, got {} types: {names:?}",
        names.len()
    );
}

#[test]
fn json_payloads_are_values_on_a_json_wire_and_text_on_a_binary_one() {
    let value = proto::Json(serde_json::json!({"a": [1, 2, {"b": "c"}]}));

    let json = serde_json::to_string(&value).unwrap();
    assert_eq!(
        json, r#"{"a":[1,2,{"b":"c"}]}"#,
        "JSON must carry the value itself"
    );
    let back: proto::Json = serde_json::from_str(&json).unwrap();
    assert_eq!(back, value);

    let bytes = postcard::to_allocvec(&value).unwrap();
    let back: proto::Json = postcard::from_bytes(&bytes).unwrap();
    assert_eq!(back, value, "postcard carries the text and re-parses it");
}
